name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Gradle
      run: ./gradlew test
    - name: Build Release AAB
      run: ./gradlew bundleRelease
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDirectory: Application/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        # key/store passwords are redundant security layers in this context
        alias: upload-self-cert
        keyStorePassword: '123456'
        keyPassword: '123456'
    - uses: actions/upload-artifact@v2
      with:
        name: Signed app bundle
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
        retention-days: 1
